language: node_js
sudo: required
dist: trusty
branches:
  only:
    - master
node_js:
  - "6"
addons:
  postgresql: "9.5"

before_install:
  - npm install pg sequelize
  - createuser -s -w username1
  - psql -d template1 -c "ALTER USER username1 WITH PASSWORD 'password1';"
  - psql -d template1 -c "create database dbname1;"
  - psql -d template1 -c "create database dbname2;"